// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const aws = {
  url: 'https://g45oh7yjzrfwfixrnhj7vgomda.appsync-api.us-east-2.amazonaws.com/graphql',
  region: 'us-east-2',
  auth: {
    type: 'API_KEY',
    // apiKey: 'da2-o2it5o2qava33m4gu5vk2bsz7u',
    apiKey: 'da2-eq2ssb4cmjcaponipjwhpigzyi',
  },
  disableOffline: true,
};

export default aws;
